system/core/Hooks.php
Let override hooks via environment-specific config.
Also for consistency with config `autoload.php`, `routes.php`, etc.
=> Change order of hooks loading

user_guide_src/source/general/reserved_names.rst
Very legacy stuff :)
I had a hard time digging to understand why the "Default" [was added](https://github.com/bcit-ci/CodeIgniter/commit/c47eb1e3009cb4d0760748c9c1fe029fb988dd55), before I try and understand it is simply the PHP keyword...
So basically, the rule is: « Don't name your controller "Index" or any [PHP keyword](http://php.net/manual/en/reserved.keywords.php). » (the "CI_Controller" is quite obvious)
=> Update reserved controller names

system/database/DB.php
When a DSN string is supplied and it contains parameters such as
"db_debug=TRUE", var_export will currently output the parsable string
representation of the variable. By setting the second parameter to TRUE,
the output is killed.
=> var_export in DB.php outputting string

system/core/Log.php, user_guide_src/source/changelog.rst
Allows to utilize "u" date format character for log entries. Support for this was added in PHP 5.2.2.
=> Support for microseconds in CI_Log

system/libraries/Typography.php
Hello,
This `$paragraph = FALSE` local variable is declared but never used.
=> Library Typography Cleaning

user_guide_src/source/libraries/sessions.rst
This mistake was pointed out to me ... it looks like the session table create command suggests "session_id" as the primary key, when it should actually say "id".
=> Session writeup error?

system/language/english/form_validation_lang.php, system/libraries/Form_validation.php, user_guide_src/source/changelog.rst, user_guide_src/source/libraries/form_validation.rst
Added support for the following functions:
Between - numeric value should be within a given range
In / Not In - string should be in/not in a list of allowed values
Date - string should be a valid date
Before Date / After Date - date should fall between a given date range
=> Extending form validation methods

system/libraries/Cache/Cache.php
$ci = &get_instance();
$ci->load->driver('cache', array('adapter' => 'memcached', 'backup' => 'file'));
$ci->cache->get('cache_key');  // if the Memcached(Memcache) Extension does not exist, it will not work.
// Fatal error:  Call to a member function get() on a non-object in .../system/libraries/Cache/drivers/Cache_memcached.php on line 50
=> fix cannot use backup driver

system/database/drivers/pdo/subdrivers/pdo_4d_forge.php
Hello,
Fix a wrong var name in class CI_DB_pdo_4d_forge::_attr_type
=> Fix a wrong var name in class CI_DB_pdo_4d_forge

system/helpers/form_helper.php, user_guide_src/source/changelog.rst, user_guide_src/source/helpers/form_helper.rst
Wouldn't it be a good idea to allow for not escaped html in set_value()?
=> Allow not-escaping the value in set_value()

index.php
If code igniter is located inside a folder named like SELF (eg. index.php), the FCPATH constant will have an incorrect value.
=> Fix incorrect FCPATH when a folder is named SELF

system/libraries/Session/drivers/Session_files_driver.php
I noticed this check in the session gc code isn't particularly reliable. First, it ignores the cookie name which is the obvious thing to use to check if the file is a CI session file. Secondly it assumes the session id is a 40 character hex string which is not a valid assumption.
=> Use session cookie name in gc check

system/libraries/Email.php
Hi there,
You'll find that if CodeIgniter cannot find the SERVER_NAME it will fallback to "localhost.localdomain" on line 2179 of "system/libraries/Email.php":
* https://github.com/bcit-ci/CodeIgniter/blob/21898a45f323bb74ef6e5ee8cf21c3397467665b/system/libraries/Email.php#L2179
This use of "localhost.localdomain" violates the standards outlined in the RFC.
Instead when a valid hostname is not available it must use an IP literal,
eg: "HELO [1.2.3.4]" instead of "HELO localhost.localdomain".
Failure to comply with the RFC will result in rejection from many mail servers
and will see your IP added to blacklists which will prevent your mail from
reaching the intended recipient.
From CBL:
There are two basic types of detections that land an IP in this page. RFC2821 section 4.1.1.1 says that …
=> Fix HELO localhost.localdomain violates RFC standards

system/core/Input.php, user_guide_src/source/changelog.rst, user_guide_src/source/libraries/input.rst
There might be cases were a client sends a request with data not in the key1=value1&key2=value2&... fashion for those cases I've added the raw_input_stream.
The input_stream function has been modified to get the data from raw_input_stream.
json_input_stream has been added for cases where the body of the request is in a json format.
Some notes:
$_input_stream has been preserved cause some people might be using it on a extension of the class, even though since 3.0 it's a pre-release version maybe it could be deleted.
On the other hand and even though it's not implemented maybe it would be better (for performance) to just parse both the input / json once, and leave it on a variable, to avoid parsing on the next call.
=> Added support for raw_input_stream and json_input_stream

system/database/DB_query_builder.php, user_guide_src/source/changelog.rst, user_guide_src/source/database/query_builder.rst
On line 1358 of file 'system/database/DB_query_builder.php'，function count_all_results() will call reset_select(), and this will reset the condition of select query.
However, in some case, we need to get the results as well as count. For example, in pagination, we need to count all the results, but only results of 0-20 using limit.
If we code as
$count = $this->db->count_all_results();//get total numbers
$this->db->limit(0, 20);//get first 20
$data = $this->db->get()->result();//this will not work
So, I suggest to add a parameter with boolean value to judge whether to call reset_select().
=> count_all_results() with $this->reset_select() 

user_guide_src/source/libraries/uri.rst
Changed "and" to "an". Editing the file online on github.com shows the last line of the file as changed, even though I didn't change it at all. It keeps doing that so I don't know how to avoid it. What I really changed is only line 113.
=> Fixed a typo in uri.rst documentation

system/libraries/Cache/drivers/Cache_redis.php
It was trying to use sAdd as a check if the key was created, but that will return false if it is already present in the set.
=> Fixed redis cache save logic

system/core/Common.php
Fix: array_fill() throws an error if count($var) is 0
Signed-off-by: Joshua Logsdon <logsdon.joshua@gmail.com>
=> system/core/Common.php, function html_escape

tests/codeigniter/libraries/Form_validation_test.php
Currently tests for set_select, set_radio, and set_checkbox are failing. I've added an inline comment briefly describing the cause of the failure. Please let me know if the test case should be failing as designed (i.e. form_validation is working as expected).
Signed off by:
djwoods <d.woods92@gmail.com>
=> More CI_Form_validation unit tests

system/libraries/Encryption.php
Fixed a typo in the HMAC array list, the "algorithms" word of the comment was mistyped.
=> Fixed typo

user_guide_src/source/database/forge.rst
At current the documentation does not distinguish between DROP TABLE IF EXISTS table_name and DROP TABLE table_name. As seen by the DB_forge.php class in system/database; the function accepts a Boolean as the second parameter as to whether or not to apply the IF EXISTS mysql condition.
=> Edit dbforge drop_table line 230

system/libraries/Zip.php
This pull request solves an issue with the $root_path's slashes not matching up with the $name it is replacing when $preserve_filepath is set to FALSE.
=> Matched root_path's slashes with the name being replaced in the Zip::read_dir() library

system/database/DB_query_builder.php
$this->db->like('name',$value,'AFTER') returns LIKE '%$value%'. Safer to lowercase in case of UPPERCASE habits.
=> #3727 Lowercase $side variable for $this->db->like() in Query Builder

system/core/Output.php, user_guide_src/source/changelog.rst
The timestamp of the created cache file should be taken, instead of the cache directory.
Reported at CodeIgniter forum: http://forum.codeigniter.com/thread-61534.html
=> Output cache: Fixing a wrong timestamp. Credits to khoggatt (CodeIgniter forum).

system/libraries/Cache/Cache.php
Continuation of #3800. I accidentally deleted the branch and GitHub won't update the old PR anymore.
This reverts the previous variable renaming and removes the foreach loop in favour of an if condition.
=> Cache Library Clean-up

user_guide_src/source/general/controllers.rst, user_guide_src/source/libraries/security.rst
Corrected "csrf_regenerate" in libraries/security.rst (it read "csrf_regeneration", incorrect per source code).
Corrected "blog" as default controller in general/controllers.rst (it read "Blog", not per convention).
=> Fix typos in user guide.

application/config/mimes.php
i was facing error while uploading 3GP based video file using codeigniter based upload class because of MIMES check failure, while cross-checking the form POST request i notice that mime type of 3GP video file is sending as "video/3gpp" which is missing from mimes config file, so i added the same into mimes config file.
=> MIMES : added new mime type for 3gp based video file upload

.gitattributes
This basically just removes a number of development-only files (like the user guide source and our tests) from any installs made through composer with the --prefer-dist flag set. 
Helps create a faster install with less unnecessary files to new projects.
=> GitAttributes file to clean up composer installs

system/database/drivers/oci8/oci8_driver.php, user_guide_src/source/changelog.rst
When you're using oracle databases and want to retrieve column information through the function field_data($table) you get the following notice: 
- Notice: Undefined property: stdClass::$COLUMN_DEFAULT in system/database/drivers/oci8/oci8_driver.php on line 576;
This happens because the oci8 driver tries to access a property that does not exist on query used to get field information. Checking the code we see a small validation to set default value, but the variable $default is not used. So we fix this bug by simply changing:
$retval[$i]->default = $query[$i]->COLUMN_DEFAULT;
to 
$retval[$i]->default = $default;
Bug fixed. No more notices and the properly value is set.
=> Fixed bug - using field_data() on Oracle databases

user_guide_src/source/general/security.rst
In the documentation at user_guide/general/security.html#best-practices, the 3-item list has a superfluous parenthetical that is also misplaced.
This parenthetical currently is at the end of the first list item, though it refers to a step that can replace the first item. As per narfbg's request in PR https://github.com/bcit-ci/CodeIgniter/pull/3915, this change removes the parenthetical entirely.
The change is:
BEFORE:
#. Validate the data to ensure it conforms to the correct type, length,
size, etc. (sometimes this step can replace step one)
#. Filter the data as if it were tainted.
#. Escape the data before submitting it into your database or outputting
it to a browser.
AFTER:
#. Validate the data to ensure it conforms to the correct type, length,
size, etc.
#. Filter the data as if it …
=> Remove superfluous *Best Practices* parenthetical

system/database/drivers/pdo/subdrivers/pdo_sqlite_forge.php
http://www.sqlite.org/changes.html
> IF EXISTS and IF NOT EXISTS clauses on CREATE/DROP TABLE/INDEX.
=> sqlite < 3.3 unsuported `_drop_table_if`

system/libraries/Cache/Cache.php
```php
$this->load->driver('cache',
array('adapter' => 'redis', 'backup' => 'file', 'key_prefix' => 'my_')
);
$this->cache->save('test', 100);
$this->cache->get('test'); //100
/*
* increment test
* Expected result: 101
* Actual result: 1
*/
$this->cache->increment('test');
```
=> supported key_prefix on `increment` and `decrement`

system/database/drivers/pdo/subdrivers/pdo_sqlite_driver.php, system/database/drivers/sqlite3/sqlite3_driver.php, user_guide_src/source/changelog.rst
Fatal error: Cannot use object of type SQLite3 as array
=> fix SQlite3 list_fields

user_guide_src/source/database/forge.rst
If you pass strings to the add_field() methods you won't be able to follow those by add_key() methods on those fields.
=> Important note on adding keys add_field() with strings

system/helpers/form_helper.php, user_guide_src/source/changelog.rst, user_guide_src/source/helpers/form_helper.rst
Extra attributes in form methods can now all be passed as arrays or strings, form_dropdown and form_open already behaved that way.
=> made all form helpers consistent regarding extra attributes

system/libraries/Pagination.php
When base_url is a URL based on protocol, like "//www.google.com" the double slash regex kills the first "//".
=> Fixes pagination with relative URL

system/core/Output.php
According to documentation, to manually delete cache for page `/foo/bar` we should run `$this->output->delete_cache('/foo/bar')`, but in this case MD5 hash will be calculated for `http://site.com//foo/bar` and this is why, we should pass `$uri` without beginning slash (ie, `foo/bar`). But the problem is that there is no way to delete cache for home page because:
1) `$this->output->delete_cache('/')` — MD5 hash will be calculated for `http://site.com//` and cache file will not be deleted.
2) `$this->output->delete_cache('')` — MD5 hash will be calculated for `http://site.com/%CURRENT_PAGE%` and again, cache file will not be deleted.
Trimming the beginning slash, we enable ability to delete cache for home page by calling `$this->output->delete_cache('/')`. Also, this method will work as …
=> Bug Fix manually delete caching method and improving Cache Query String behaviour

system/helpers/path_helper.php
The currently implemented method marks all IPs between 0.0.0.0 - 999.999.999.999 as valid IP Address. Which generates false positives as any IP after 255.255.255.255 is not a valid IP address.
Also, there is no check for IPv6 IP addresses.
filter_var() solves both the issues.
=> IP checking false positives and no IPv6 check

user_guide_src/source/database/results.rst
Since some drivers must prefetch the entire result set and count the results, this practice should not be encouraged in the user guide since: 
- `result()`, `result_array()`, and `result_object()` will return an empty array with no results
- `row`, `row_array()` and `row_object()` will return NULL if no result.
=> Removing use of ->num_rows() in DB results docs.

application/views/errors/cli/error_exception.php, application/views/errors/cli/error_php.php
Fix coding style exactly the same in two error templates.
~~~diff
--- error_exception.php	2015-07-21 08:21:16.000000000 +0900
+++ error_php.php	2015-07-21 08:13:20.000000000 +0900
@@ -1,16 +1,16 @@
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
-An uncaught Exception was encountered
+A PHP Error was encountered
-Type:     <?php echo get_class($exception), "\n"; ?>
+Severity: <?php echo $severity, "\n"; ?>
Message:  <?php echo $message, "\n"; ?>
-Filename: <?php echo $exception->getFile(), "\n"; ?>
-Line Number: <?php echo $exception->getLine(); ?>
+Filename: <?php echo $filepath, "\n"; ?>
+Line Number: <?php echo $line; ?>
<?php if (defined('SHOW_DEBUG_BACKTRACE') && SHOW_DEBUG_BACKTRACE === TRUE): ?>
Backtrace:
-<?php	foreach ($exception->getTrace() as $error): …
=> Fix coding style in CLI error templates

user_guide_src/source/helpers/text_helper.rst
The `word_wrap` function in text helper should returns a **Word-wrapped string** , but the document gives a full string with no wrap, this may be confusing and causes misunderstanding.
=> The produce of word_wrap function in text helper is not clear

user_guide_src/source/helpers/html_helper.rst
Ordered HTML list is generated by ol() function, not ul().
=> Correct the notes of html_helper ul() function

system/libraries/Profiler.php
This checking can be done by calling set_sections method when initialize profiler .
=> Reduce once $config['query_toggle_count'] checking

user_guide_src/source/libraries/image_lib.rst
The mentioned default value has been corrected within the documentation accordingly.
https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Image_lib.php#L264
=> Image_lib, the default value of the option 'wm_shadow_distance' is 2 actually.

system/database/DB.php
We can simplify this if statement since empty() is checking if variable is set and if it's empty in the same time.
=> Change if is not set or count equals zero into if empty

system/libraries/Form_validation.php
I ran into a problem where I wanted to use regex_match in the form validation library, but when I put a pipe character in my expression, things broke because set_rules() does a blind explode on pipe. I changed it so it will split the string on any pipe character not contained in square brackets.
Example:
```
$this->form_validation->set_rules('fru-rt-loan-type', 'Loan Type', 'required|regex_match[(refinance|purchase)]|alpha')
```
Causes:
```
Unable to access an error message corresponding to your field name Loan Type.(regex_match[(refinance)
```
=> Form validation library to allow the pipe character within brackets

system/libraries/Form_validation.php, user_guide_src/source/changelog.rst, user_guide_src/source/libraries/form_validation.rst
When checking multiple arrays using form_validation you have to call reset_validation between each separate check due to the instance of the library being a singleton.  The issue comes in when the settings are loaded from a config file as they are initially loaded from a parameter in the constructor, but are set to an empty array when resetting the class.  To get around this issue a copy of the config parameter is made and then the copy is used to reset the rules when clearing.
=> Persist config file settings when resetting form_validation

system/database/DB_utility.php
After applying this change, I am able to export 50K rows at around 5 seconds. meanwhile the old version is giving me timeouts.
=> Optimize csv_from_result speed.

user_guide_src/source/_themes/sphinx_rtd_theme/breadcrumbs.html, user_guide_src/source/_themes/sphinx_rtd_theme/static/css/citheme.css, user_guide_src/source/_themes/sphinx_rtd_theme/static/js/theme.js
I would like to suggest that we disable pulldown menu on small screens since this feature is designed for desktop devices and it does not function well on mobile devices.
For example, when enabling pulldown menu on mobile devices, the bar icon will not disappear and a blank side bar will show up after clicking the bar icon.
And while the pulldown menu is helpful on large screens, it is not really easy to view on mobile devices.
As the recent release started to offer Epub version of docs so that users could have one more alternative on mobiles, I think it would be safe to remove this functionality on small screen.
=> disable pulldown menu on mobile devices

system/core/Lang.php, tests/codeigniter/core/Lang_test.php
related to issue #4189 
When the lang file could not be found, an exception will be thrown. Test cases already exist. By doing this, the error page would not be automatically rendered. If there is a need, user should call error page rendering in their exception handler(not sure if this is an issue). 
No particular changes are needed for the user guide.
=> refactor exceptions for core/Lang

system/core/Config.php
Now that `base_url` is being calculated using `SERVER_ADDR` instead of `HTTP_HOST`, it no longer works on IPv6 hosts. This fixes the problem by surrounding literal IPv6 addresses with proper [square brackets]. IPv4 addresses are not affected.
`http://::1/some/controller` ← this is not valid
`http://[::1]/some/controller` ← this is valid
=> Build base_url correctly if SERVER_ADDR is IPv6

tests/codeigniter/core/Loader_test.php
These changes are separated from #4220 as they are not targeting on error handling but improving test coverages. A specific explanation of the changes could be found in the comment. A note is that the prefix "CI Error" should be removed once the error handling code is merged.
=> modify and add test cases for Loader class to test more exceptions

system/core/Loader.php, tests/codeigniter/core/Loader_test.php
- Change show_error() to throw exceptions in system/core/Loader
- Changes in tests
- "CI: Error" prefix is removed.
- fixed one test of test_library(): the previous test tried to create a library without class, but it did not call `ci_vfs_create()` properly(no `ucfirst()` is used), so it actually was testing non-existent library files.
- added a test case to test loading an empty library file. A RuntimeException with message `'Non-existent class: '.ucfirst($lib)` is excepted.
- added a test case to test loading a new library with previously used object name. An exception with message `"Resource '".$obj."' already exists and is not a ".$class." instance."` is expected.
- No changes are needed for user guides
=> refactor exceptions for Loader

user_guide_src/source/database/configuration.rst
"it" changed to "in" on line 10. "in" seems like the correct word to be used there. Small change.
=> Grammar correction in database configuration guide

contributing.md, readme.rst, user_guide_src/source/contributing/index.rst, user_guide_src/source/general/requirements.rst, user_guide_src/source/general/styleguide.rst
PHP 5.4 reached end of life
Signed-off-by: Claudio Galdiolo <claudio.galdiolo@gmail.com>
=> [ci skip] Make it clear that PHP <5.5 usage is discouraged

user_guide_src/source/libraries/form_validation.rst
With case-sensitive filesystem, visiting example.com/index.php/form/ returns a '404 Page Not Found' error
=> [ci skip] Fix file name in documentation

user_guide_src/source/database/db_driver_reference.rst, user_guide_src/source/helpers/cookie_helper.rst, user_guide_src/source/helpers/form_helper.rst, user_guide_src/source/libraries/sessions.rst, user_guide_src/source/libraries/trackback.rst
Sphinx generates incomplete/incorrect HTML output because there are
mismatched brackets in the documentation.
Signed-off-by: Phil Scherer <pscher1@umbc.edu>
=> Fix mismatched brackets in documentation

system/core/Loader.php, user_guide_src/source/libraries/loader.rst
add documentation for #4220 
part of #4189 
In Loader.php, documentation is added for every function which directly triggers an exception.
In the user guide, documentation of exceptions is added for every function which is possible to throw an exception during the execution(directly or indirectly through internal functions).
=> add documentation of exceptions for Loader

user_guide_src/source/helpers/form_helper.rst
`echo form_checkbox('newsletter', 'accept', TRUE, $js)` lines are missing the semicolon at the end of the line.
=> [typo] missing ; at end of PHP lines 464 and 469

application/config/constants.php
The word "destructive" was misspelled in the conditional portion.
=> Fix type in default constants configuration

system/helpers/html_helper.php, user_guide_src/source/helpers/html_helper.rst
HTML Helper changed to generate HTML 5 declaration as default in place of XHTML 1.0 Strict when using `doctype()` function.
=> Default doctype is now HTML 5

system/libraries/Pagination.php
After upgrading to CI3 I noticed that developers are able to determine the current page counter for pagination based on
* Explicit query string parameters
* URI segment configuration
In earlier versions a developer could still set the current page counter in the pagination lib directly which is useful if you want to use pagination with HTTP POST instead of GET. This could be done by passing
$config['cur_page']  = '10';
to the pagination function for link generation. Currently this code has changed and will always try to check whether the uri segment is a valid number or not, even if the cur_page variable was passed in the associative array, and fallback to zero if it fails to validate that result.
This can be easily resolved by checking whether the counter was already set with a valid …
=> Respect $config['cur_page'] variable for pagination

user_guide_src/source/contributing/index.rst
Fixed minor typographical error in the documentation, `contributing/index.html`
**From**
By signing your work in this manner, you certify to a “Developer’s Certificate _**or**_ Origin”.
**To**
By signing your work in this manner, you certify to a “Developer’s Certificate _**of**_ Origin”.
=> (Documentation) Fixed minor typographical error

system/libraries/Session/drivers/Session_redis_driver.php
I'm working on an application that will eventually save session data, but doesn't yet (other than for user logins).  Therefore, the session driver is loaded on each pageview but nothing is written to it.  I noticed that I was getting a `PHP warning: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct ()`, and spent some time debugging.
It seems that if writing an empty session (that is, where `$session_data` is a blank string) to redis, the key isn't actually created in the redis store (expected redis behaviour, I guess).  Therefore, when the driver then runs the `setTimeout` function on that key, it returns 0, which triggers a failure in the `session_write_close` handler.
Therefore, my fix is to simply not set …
=> Fix PHP session_write_close warning when writing empty session to Redis

user_guide_src/source/installation/index.rst, user_guide_src/source/installation/troubleshooting.rst, user_guide_src/source/overview/at_a_glance.rst, user_guide_src/source/tutorial/create_news_items.rst, user_guide_src/source/tutorial/static_pages.rst
Consistent formatting for first 4 sections of documentation
- File paths are made _italicised_
- Method names and variables are formatted with `inline code`
=> (Documentation) Consistent formatting of file paths and inline code

system/helpers/inflector_helper.php
Since the separator could be arbitrary, it needs to be preg-escaped.
=> hunanize() helper: Escaping the $separator argument.

system/core/Log.php
- Extracted the `CI_Log` line formatting into a protected
function `_format_log_line()` so as to make it easy to
change the log line format via extending the class and
overriding the method.
=> Refactored the `CI_Log` line formatting

system/libraries/Form_validation.php
Refactored the logic for getting an error message related to a rule.
Don't want to have the same logic in two places.
priority wise:
1. check if a custom message is defined through validation config row.
2. check if a custom message has been set using the set_message() function
3. check if we have an error message in lang file
4. DEPRECATED support for non-prefixed keys, in lang file again
5. error message not found -> default to `"form_validation_error_message_not_set"`
=> Refactor: logic to get the rule's error message

system/libraries/Session/drivers/Session_redis_driver.php
set $this->_lock_key to NULL after close
When calling session_start() again to re-use session after calling session_write_close(), the driver will call _get_lock(). Inside _get_lock, it will check whether the lock has been already gained by checking _lock_key variable. But before this commit, when calling session_write_close(), the close() method did not clear the _lock_key. Next, when calling _get_lock(), it found _lock_key already exist but the lock had been released, so _get_lock failed.
Signed-off-by: roastduck <beantang.tang@gmail.com>
=> clean current lock key in redis session driver

system/libraries/Cache/drivers/Cache_memcached.php
`Memcache` and `Memcached` have different methods to closing connection.
=> Added the destructor (disconnect from memcache(d))

system/libraries/Cache/drivers/Cache_redis.php
It is an improved version.
See previous at #4527 .
By the way, @narfbg  **you are wrong!**
> > Ok. What would we get if we set a boolean value like FALSE or a NULL value? We will get the same value "". 
> > Worth mentioning that "" !== FALSE and "" !== NULL.
> Would we? I'm quite certain that Redis stores NULLs as NULLs and booleans as booleans.
Redis stores NULLs as NULLs and booleans as booleans but PHPRedis returns they as `string`. Check it yourself.
=> Setup the data defining for stored data (redis)

system/libraries/Cache/drivers/Cache_redis.php
Added a `expireAt` call in the `save()` method.
Now the `save()` method with passed `ttl` argument works correctly. 
The `get_metadata()` works correctly.
=> Added the expiration to save() method

system/libraries/Cache/drivers/Cache_redis.php, user_guide_src/source/libraries/caching.rst
Removed the second condition of connectivity for unix sockets in `Redis::__construct()` method.
It is unnecessary because we can use `host` and `port` parameters.
=> Removed the second condition for unix sockets (redis)

user_guide_src/source/libraries/email.rst
Today I am creating a sample email with embedded image. I am following example from CodeIgniter user guide:
`$this->email->message('<img src='cid:". $cid ."' alt="photo1" />');`
But apparently the code sample is not working. The embedded image is not showing on the email (I am aware about SPF/DKIM, I am using SPF and the result is `pass`). After couple of retries I am just removing the double quotes from `$cid`:
`$this->email->message('<img src="cid:'. $cid .'" alt="photo1" />');`
And now its working. The embedded image on the email finally showed up.
I am changing the code sample so it will not confuse other developers.
=> Removed double quotes on $cid

user_guide_src/source/tutorial/create_news_items.rst
I found a unnecessary backslash on a following page.
http://www.codeigniter.com/user_guide/tutorial/create_news_items.html
=> Remove unnecessary backslash from user guide

system/libraries/Email.php
The issue has been fixed by separating attachments into 2 different multiparts for html emails
- Embedded attachments are generated into a multipart/related part
- Non-embedded attachments are generated into a multipart/mixed part
Please note that this solution also works for Thunderbird.
=> Fixes #4583 by separating attachments to related and mixed multiparts

readme.rst
PHP 5.5 end of life is July 10, 2016
=> [ci skip] recommend PHP >= 5.6

system/libraries/Upload.php
I use the following code for benchmark test.
`
/* just comment */
$name = "test_benchmark.cpp.cpp";
$ext = ".cpp";		
$raw_name = "";
$this->benchmark->mark("positive_start");
$count = 1000000;
for($i = 0; $i < $count; $i++){			
$raw_name = substr($name, 0, strlen($name) - strlen($ext));			
}
$this->benchmark->mark("positive_end");
echo "Positive length elapsed ".$this->benchmark->elapsed_time("positive_start", "positive_end")." seconds. "."<br>";
$this->benchmark->mark("negative_start");
for($i = 0; $i < $count; $i++){
$raw_name = substr($name, 0, - strlen($ext));
}
$this->benchmark->mark("negative_end");
echo "Negative length elapsed ".$this->benchmark->elapsed_time("negative_start", "negative_end")." seconds. "."<br>";`
The output is as follows:
Positive length elapsed 4.1075 seconds …
=> Use negative length for speeding up.

user_guide_src/source/libraries/sessions.rst
Changed `umark_flash()` and `umark_temp()` to `unmark_flash()` and `unmark_temp()` to match with their respective methods in the Session class.
_I suggest the docs reflect as soon as possible. It's causing issues for beginners..._
:+1:
=> Fixed typos

system/core/Common.php
In case of upper-case HTTP header field value.
Signed-off-by: tianhe1986 <w1s2j3229@163.com>
=> Call strtolower before comparing $_SERVER['HTTP_X_FORWARDED_PROTO'].

system/core/Common.php, tests/codeigniter/core/Common_test.php
In case of passing upper case query string. The return value of urlencode is also upper case.
Signed-off-by: tianhe1986 <w1s2j3229@163.com>
=> Replace url_encoded invisible characters case-insensitively.

system/libraries/Unit_test.php
It should be "res_datatype" which is listed in $_test_items_visible rather than "test_res_datatype".
=> CI_Unit_test: Fix name of visible test items.

system/libraries/Unit_test.php
"is_double" is already an alias of "is_float".
=> CI_Unit_test: Do not replace "is_double" with "is_float".

system/libraries/Cache/drivers/Cache_file.php
In case of directory, and also keeping consist with  `_get` in [Cache_file.php](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Cache/drivers/Cache_file.php#L270)
=> Cache_file: use is_file() for checking instead of file_exists().

system/libraries/Cache/drivers/Cache_file.php
In case of mtime changed and also keeping the same way implemented  in `_get()` , see [Cache_file.php](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Cache/drivers/Cache_file.php#L277)
=> Cache_file: use $data['time'] for calculating expired time.

system/core/Common.php
Compile-time parse errors should also be treated in the same way as fatal errors.
=> Common: Adding E_PARSE in error judgment.

system/core/compat/standard.php
Keeping in consist with original `hex2bin()` function.
=> Standard: filtering "resource" type in hex2bin()

system/core/URI.php
When using the uri_to_assoc call multiple times within 1 request, with multiple default values for each call, only the default values of the first call are used. All subsequent calls will have used the cached values.
It might be useful to call this multiple times. For example, when you want to do a general check in your __construct for a param that always has to be set, but the controller methods might expect different parameters.
Removing this IF statement, will solve that issue.
Example:
```
public function __construct()
{
$default = ['type'];
$uri_params = $this->uri->uri_to_assoc(3, $default);
}
public function view()
{
$default = ['type', 'sort_order'];  // Sort_order can be optional 
$uri_params = $this->uri->uri_to_assoc(3, $default);
$items = $some_object->get($uri_params['type'], …
```
=> Removed URI_TO_ASSOC "caching"

system/database/drivers/mysqli/mysqli_driver.php
Updated codes to pass MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT flag
=> supplied flag to turn off mysqli SSL verification if ssl_verify passed as false

system/helpers/form_helper.php
I propose to remove the inline style "display:none" for hidden form fields.
1. I know of no browser that actually displays hidden form fields, so setting the style is redundant.
2. I can not imagine situations where developers rely on this style being present.
3. It generates an error when inline styles are disabled in a CSP header.
3 is my main reason for removing the style.
=> Remove inline style from hidden fields

system/helpers/captcha_helper.php, system/helpers/download_helper.php
At this point, captcha helper doesn't remove .png files (expired files) if the imagepng was used at captcha creation (and not jpg).
This pull request solves this issue.
=> Fix file deletion on captcha helper

system/libraries/Xmlrpc.php, user_guide_src/source/libraries/xmlrpc.rst
Set timeout after socket open, for subsequent operations.
Eliminated usleep(...) in response handling loop
Updated user guide page for xmlrpc library
=> Fix xmlrpc timeout, #4843

system/libraries/Table.php, user_guide_src/source/libraries/table.rst
- when calling `clear()`, caption should be cleared too;
- method chaining wasn't working when calling `set_caption()` method;
- updated docs for these changes.
=> Small fix for HTML Table library

system/database/DB_driver.php, system/database/drivers/odbc/odbc_driver.php
I use the following code in controller.
```
$this->load->database();
$sql = 'select * from reader where reader_id = ? and level = ? and tag = "1?2"';
$binds = ['3456', '888'];
$compiled_sql = $this->db->compile_binds($sql, $binds);
echo $compiled_sql;
```
The expected output should be
`select * from reader where reader_id = '3456' and level = '888' and tag = "1?2"`
However,  get
`select * from reader where reader_id = ? and level = ? and tag = "1?2"`
It is because that double quote does not be matched in `compile_binds()`.
And the same with `is_write_type()`.
=> Match both single and double quote in DB_driver

system/helpers/download_helper.php, user_guide_src/source/helpers/download_helper.rst
When using download helper, I can see 3 use cases:
1. You have the content of the file to be downloaded and you provide the name of file as it should be downloaded;
2. You have to read the content from disk and the downloaded file name will be the same as read file;
3. You have to read the content from disk and you provide the name of file as it should be downloaded.
At this point, the first 2 do exist and work. However, 3rd point can be achieved by dev by renaming the local file and then, most probably, renaming it back to original filename.
This PR adds the 3rd use case by letting you provide an array with one item in first param: [local file full path => browser filename].
=> Download helper added new use case 

system/database/drivers/pdo/subdrivers/pdo_sqlite_driver.php
`order_by('column_name', 'random')` expects the driver's `$_random_keyword` to contain array with minimum two elements https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/DB_query_builder.php#L1191
Having string content generates invalid query like `SELECT * FROM table ORDER BY;`
Signed-off-by: aquilax <aquilax@gmail.com>
=> Fix order_by random for pdo(sqlite) driver

user_guide_src/source/general/core_classes.rst, user_guide_src/source/general/models.rst
I consider an empty constructor just calling the parent constructor pointless, and believe they should never exist, and as such should never be "suggested" by the documentation. In this PR I removed one such constructor, and added similar comments to others, where they exist in documentation to prove a point.
=> Remove needless constructor in model general topics documentation

system/database/DB_query_builder.php
Updated from pull request #4955
See PR #4955
=> Fix the bug: DB_query_build does not use cached "group_by"

system/database/drivers/oci8/oci8_forge.php
I ran the following code and the following error occurred.
Code:
```php
$this->dbforge->add_column('sample', [
'column_name1' => [
'type' => 'char',
'default' => '0'
],
'column_name2' => [
'type' => 'char',
'default' => '0'
]
]);
```
Error
```shell
A PHP Error was encountered
Severity:    Notice
Message:     Array to string conversion
Filename:    /codeigniter/system/database/drivers/oci8/oci8_forge.php
Line Number: 136
```
=> oci8_forge add column bug fix

system/language/english/imglib_lang.php, system/libraries/Image_lib.php
The get_image_properties method should return false if the image isn't valid just like if it isn't found.
At the moment the method returns 
```
array (
'width' => NULL,
'height' => NULL,
'image_type' => NULL,
'size_str' => NULL,
'mime_type' => 'image/jpg',
)
```
because it interprets the `false` as array which results in `NULL`.
=> Image_lib::get_image_properties invalid image handling

system/helpers/download_helper.php
CodeIgniter uses the classic combination of `fopen` and `fread` functions to achieve the reading of a file, if a path is provided to `force_download` helper function. 
The only problem about this combination is that `fread` uses a hardcoded value for chunk size: 1048576 (1MB). This may be a memory usage problem on high-load applications developed with CodeIgniter (even on a dedicated server), and can be avoided by using PHP's function [`readfile`](php.net/manual/en/function.readfile.php), which is handling the reading according to server status. As you can see from official docs, it shouldn't create any memory problems, even on big files.
=> Download helper improvement on reading phase

system/core/Loader.php
Change the undefined variable $object to $vars when calling get_object_vars().
This fixes an error when passing an object to a view.
=> Fix Undefined variable: object error

system/core/Loader.php
We want to exactly match a dot, so we have to escape it.
I found the bug because in my project I load an helper named `session_php_helper.php`, so the `_php` part gets removed and the `session_helper.php` helper gets loaded instead, this way not even an error was shown.
=> Fixed regex used for loading helpers

system/database/DB_query_builder.php
Set `$_protect_identifiers` to `TRUE` and also set `dbprefix` to `ok_`.
Then I used the following code:
```
$this->db->start_cache();
$this->db->select('us.name');
$this->db->from('user as us');
$this->db->stop_cache();
$sql = $this->db->get_compiled_select('');
echo $sql."\n";
$sql = $this->db->get_compiled_select('');
echo $sql."\n";
```
and got
```
SELECT `us`.`name` FROM `ok_user` as `us`
SELECT `ok_us`.`name` FROM `ok_user` as `us`
```
The table prefix was not properly processed in `CI_DB_query_builder::_merge_cache()`. 
And the similar situation when using qb cache with alias in JOIN statement.  For example,
```
$this->db->start_cache();
$this->db->select('user.name, jo.description');
$this->db->from('user');
$this->db->join('job as jo', 'user.name = jo.name'); …
```
=> Add aliased tables cache in query_builder.

system/core/Common.php
At the beginning of the function it checks whether a parameter $status_code is less than 100. Then the parameter $exit_status is formed by summing the $status_code + 9. In this case, the parameter $exit_status can not be more than 108, but somehow it is checked whether the value of the parameter $exit_status over 125. Such a situation can not occur under any circumstances.
=> Fixed show_error() for check $exit_status

system/libraries/Profiler.php
1 Session and config items may also contain single quotes.
2 `<pre>` tags are not closed.
=> Two small changes with CI_Profiler

system/core/Common.php
1 Loading global mimes config file before environment file in `get_mimes` according to the [doc](https://github.com/bcit-ci/CodeIgniter/blob/develop/user_guide_src/source/libraries/config.rst#environments).
2  `DEL`(url encoded 127) should also be removed in `remove_invisible_characters`.
=> Fix two bugs with Common Functions 

application/config/config.php, system/core/Exceptions.php, system/core/Log.php, system/core/Output.php
This always has bugged me :)
Let's be kind to the developer, don't break everything if he provided a path without trailing slash.
=> Allow to omit trailing slash in config paths

system/helpers/download_helper.php
We should not assume the passed array has its pointer set to the first element.
=> Do not fail if the array pointer is after the element

system/database/DB_driver.php
Fixes #4815.
Indeed, in SQL context there are no URL encode sequences.
=> Do not strip substrings looking like URL encode sequences

system/libraries/Cache/Cache.php, system/libraries/Cache/drivers/Cache_apcu.php
I recently work on PHP7 and APCu with CodeIgniter, but there is no built-in APCu driver.
So I create APCu cache driver and [Prefix]_Cache, but I want to use it as a built-in driver.
This is compatible with existing driver usage.
```php
$this->load->driver('cache', 
array('adapter' => 'apcu')
);
$bar = 'bar'
$this->cache->save('foo', $bar);
$this->cache->get('foo') // output 'bar'
```
=> Introduce APCu driver

system/database/DB_cache.php, system/database/DB_result.php
Hi,
when using `set_error_handler()` and matching E_WARNING, the read() method in CI_DB_Cache fails at [L146](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/database/DB_cache.php#L146), this because [`file_get_contents()`](http://php.net/file_get_contents) emits an E_WARNING when it does not find the file.
This should fix it:
````
if ( ! is_file($filepath) OR FALSE === ($cachedata = @file_get_contents($filepath)))
````
=> read() in DB_cache fails when catching E_WARNING with custom error handler

system/helpers/form_helper.php
When passing a string for extra attributes in form_label helper function, these attributes were skipped.
=> fix bad attribute handling of form_label

system/database/drivers/oci8/oci8_forge.php
I got a `ORA- 00946 : missing TO keyword` error when running the following code.
```php
$this->dbforge->modify_column('foo', [
'bar' => ['name' => 'foobar']
]);
```
Therefore, the `TO` keyword was added.
=> fix ORA- 00946

system/database/DB_query_builder.php, tests/codeigniter/database/query_builder/count_test.php
I used the following code for pagination search
```
$this->db->where('num >=', 9);
$this->db->limit(2,2);
$num = $this->db->count_all_results('test_user', false);
$query = $this->db->get();
$result = $query->result_array();
```
and found `count_all_results` generated
```
SELECT COUNT(*) AS `numrows`
FROM `test_user`
WHERE `num` >= 9
LIMIT 2, 2
```
but 
```
SELECT COUNT(*) AS `numrows`
FROM `test_user`
WHERE `num` >= 9
```
was expected.
Surely I could use `limit(X,X)` after calling `count_all_results`, however, it would be better if `LIMIT` usage be ignored with `count_all_results`.
I also thought about generating sql like this
```
SELECT COUNT(*) AS `numrows`
FROM (
SELECT *
FROM `test_user`
WHERE `num` >= 9
LIMIT 2, 2
) CI_count_all_results 
```
But it may be a rare usage.
=> Ignore LIMIT when using CI_DB_query_builder::count_all_results

system/core/Loader.php, tests/codeigniter/core/Loader_test.php
If a model does not extend the base Model class, it works fine at the first time loaded.
But when this model is loaded at the second time with a different object name,  it throws `RuntimeException`.
In fact, a exception should be thrown at the first time.
=> Always check a model be a subclass of CI_Model when loaded

system/libraries/Session/drivers/Session_memcached_driver.php, system/libraries/Session/drivers/Session_redis_driver.php
When using `redis` or `memcached` session driver, if a web-client perform multiple requests at the same time, two or more requests may get the session lock, and finally some of them would generate "Session: Error while trying to free lock for" error log.
Using `Redis::setnx` and `Memcached::add ` properly could help to decrease the probability of this race condition.
=> Decreasing the probability of race condition in session lock

system/core/Loader.php
Add array type to $library param at PHPDoc, so the IDE will not show a warning when we passing an array to it.
=> Add array identifier for library loader

system/database/DB_driver.php
I would like to get `affected_rows` when I run the following code:
```php
<?php
$sql = <<<EOD
MERGE INTO DUAL A
USING DUAL B ON (A.ID = B.ID)
WHEN MATCHED THEN
UPDATE SET A.FOO = B.BAR
WHEN NOT MATCHED THEN
INSERT (ID, FOO) VALUES (B.ID, B.BAR)
EOD;
$this->db->query($sql);
var_dump($this->db->affected_rows());
```
=> add is_write_type method for merge query

.gitignore, user_guide_src/source/database/query_builder.rst, user_guide_src/source/general/urls.rst, user_guide_src/source/libraries/input.rst, user_guide_src/source/libraries/loader.rst
Three of the user guide pages had mismatched quotes, causing sphinx problems.
urls.rst still has a block that sphinx doesn't like :(
=> Fix some mistakes in the user guide

system/helpers/url_helper.php
`auto_link('http://example.com/example/');`
Result
`<a href="http://example.com/example">http://example.com/example</a>`**/**
Fix Result
`<a href="http://example.com/example/">http://example.com/example/</a>`
=> Fix auto_link trailing slash

system/database/DB_query_builder.php
recent changes broke query ordering giving a warning in line 1238 = '$this->qb_cache_orderby = array_merge($this->qb_cache_orderby, $qb_orderby);'
the warning message was about array_merge not working with a NULL object.
this was because on subsequent re-queries, the qb_cache_orderby was set to NULL not Array() as it is should have been.  See the initial instantiation of the $this->qb_cache_orderby 
This PR should fix it.
=> Fix ORDER BY clauses being reset by count_all_results()

system/libraries/Form_validation.php, tests/codeigniter/libraries/Form_validation_test.php
Fix attempting to access data_ref before it is defined when validating an array input with multiple explicitly specified keys.
Fixes #5202.
=> Fix Error "Cannot create references to/from string offsets"

application/config/database.php, user_guide_src/source/database/configuration.rst
Missing ‘e’ in word ‘certificates’.
=> Small spelling fix

user_guide_src/source/general/urls.rst
- remove double colon before code-block
- change lexer into apacheconf
Fixes #5283
Signed-off-by: Mamat Rahmat <coderbodoh@gmail.com>
=> Fix broken .htaccess example code-block

tests/codeigniter/libraries/Form_validation_test.php
There are a number of places where `$_POST` is modified and not
reset back to its previous state. This could lead to side effects
impacting other tests. There are also a number unnecessary calls to
`reset_validation()`. A new form_validation object is already
initialized for every test in `set_up()`, so these lines do nothing
unless they are cleaning up from earlier in the same test.
To remedy this, we make the following changes:
Set `$_POST = array()` in `set_up()`, resetting to a default state for
every test run. Add a `tear_down()` method that does the same and is
called by PHPUnit's `tearDown()` after each test.
Remove now-redundant lines where tests set `$_POST = array()` at the
beginning or end of the test.
Remove unnecessary calls to `reset_validation()` intended as setup
or …
=> Clean up form validation tests

user_guide_src/source/installation/downloads.rst
CodeIgniter 2.2.6 is the latest supported version of CodeIgniter2 and the documentation (Installation Instructions » Downloading CodeIgniter) only shows CI2 links up to 2.2.3. This links can be useful when trying to upgrade from CI2 to CI3, at least to update to the latest CI2 version before shifting to CI3.
=> Download links for versions 2.2.4 to 2.2.6 added to docs

system/core/Loader.php
In the model function the $model parameter accepts either a string or an array.
=> Fixed docblock on model function. Changed @param model from string to mixed

contributing.md
When I clicked on Codeigniter repository on Contributing.md, it redirects to https://github.com/bcit-ci/CodeIgniter>, (showing 404), there is some extra greater than symbol, creating issue, so I have fixed and creating pull request for that :) .
=> Bug in documentation

system/libraries/Pagination.php
@narfbg I ran into a similar issue, Looking into the diff you provided 
https://github.com/bcit-ci/CodeIgniter/issues/4454#issuecomment-245943255
I found out that it was actually being reset, As you have to call the initialize method again to give it the urls ...etc
=> Fix issue #4454

system/database/DB_forge.php, system/database/DB_result.php, system/libraries/Email.php, system/libraries/Encryption.php, system/libraries/Session/Session.php, system/libraries/Upload.php, system/libraries/Xmlrpcs.php, tests/mocks/ci_testcase.php
I've cleaned the `else`s when we have already returned something, this saves us some lines of code :put_litter_in_its_place:
[`PHP-CS-Fixes`](https://github.com/FriendsOfPHP/PHP-CS-Fixer) helped me find them.
=> Clean elses

system/libraries/Cache/drivers/Cache_memcached.php
Just trying to keep consist with other drivers. I have tested `file`, `redis` and `apcu`, they would set a initial value when the item do not exist.
`Memcache` does not create an item if not exist refer [here ](https://secure.php.net/manual/en/memcache.increment.php#refsect1-memcache.increment-description).
`Memcached` would create an item, but only with binary protocol refer [here](https://secure.php.net/manual/en/memcached.increment.php#111187).I also tried it myself.
=> Cache_memcached: setting initial value with increment/decrement when not exist

system/libraries/Session/drivers/Session_memcached_driver.php
Just a one line change.
It should return `TRUE` when calling of `$this->_memcached->replace()` succeed. Otherwise,  it would at last fail with 30 attempts , becasue the later calling of `$this->_memcached->get()` always get the value just set.
=> Fix of Session_memcached_driver::_get_lock 

system/helpers/url_helper.php
Fixed security issue:  allowing the target page to take control of the original page
Details about the issue here: https://mathiasbynens.github.io/rel-noopener/
=> Prevent tab hijacking when using the URL helper

system/helpers/download_helper.php
When I created an application to download multibyte file name, the file name got corrupted.
Changed give force_download a header conforming to "RFC6266"
The phenomenon that the file name is garbled can be confirmed with Internet Explorer 11 older.
https://tools.ietf.org/html/rfc6266
```php
<?php
class Downloader extends CI_Controller
{
public function __construct()
{
parent::__construct();
$this->load->helper('download');
}
public function download()
{
force_download('マルチバイト.txt', 'test');
}
}
```
=> Give force_download a header conforming to RFC 6266

system/helpers/download_helper.php
link: https://github.com/bcit-ci/CodeIgniter/pull/5394
Fixed bug that download filename character code did not change 
https://github.com/bcit-ci/CodeIgniter/pull/5403/files#diff-c54549fcea24b456454689aab2d65904L156
This line is `false` unless you change the `charset` value with `set_config`.
This is because the following implementation is done in the Utf8 class
https://github.com/bcit-ci/CodeIgniter/blob/develop/system/core/Utf8.php#L65
=> Fixed bug that download filename character code did not change 

system/libraries/Image_lib.php
Allow changing file name (`Content-Disposition` header) when outputting the image by specifying the `new_name` config
=> File name changing in dynamic output image_lib

system/libraries/Zip.php
the `read_dir` method ignores files that start with a dot (like .htaccess).
I looked through the documentation and it didn't mention that the method ignores hidden files so it must be a bug.
=> Fixed bug in ZIP library

system/libraries/Image_lib.php
When processing an image, there is no need to set file permissions when using dynamic_output.
In some cases, it floods the log file with errors
ERROR  --> Severity: Warning --> chmod(): Operation not permitted ...../CodeIgniter/libraries/Image_lib.php 838
=> Update Image_lib to avoid setting file permissions when not needed

system/core/Security.php
`document.cookie` and `document.write` are filtered but can easily be evaded by `(document).cookie` and `(document).write`.
Also the `$_never_allowed_regex` checked for `document.window` which is always undefined and won't work.
It should be `window.document`.
=> Added parenthesis check around "document" elements and fixed non-existent document.window filter to window.document

system/database/DB_driver.php, system/database/DB_query_builder.php
The query builder tests if `$qb_limit` is the default value `FALSE`. So you can code like below;
// $params->limit = 0;
$this->db->limit($params->limit);
=> The value of limit can be zero

user_guide_src/source/installation/upgrade_320.rst
Not a big deal, but addresses Sphinx warning message "Title underline too short."
=> Fix sphinx warning message

system/helpers/html_helper.php
Using the Config::slash_item() method, we get double forward slashes. For example, base_url = 'http://localhost:8080/' and asset is '/assets/my_asset.css', then the generated URL would be 'http://localhost:8080//assets/my_asset.css'.
This patch fixes that, so the generated URL would be 'http://localhost:8080/assets/my_asset.css'. There is actually already an analog example in the case if index_page === TRUE, where the site_url() function is used.
=> Use Config::base_url() properly

application/config/mimes.php
As this [Wikipedia article](https://en.wikipedia.org/wiki/7z) states, the 7-Zip generated archives have the `7z` extension and the MIME id `application/x-7z-compressed`.
=> mimes.php: 7z file types changes

system/core/Input.php, tests/codeigniter/core/Input_test.php
With URL such as `http://ci.mine.cn/test/test_get?a[b]=test` and the following code
```
$something = $this->input->get('a[b]');
$something2 = $this->input->get_post('a[b]');
var_dump($something, $something2);
```
`$something` gets 'test', and `$something2` turns out to be `NULL`.  However, they are expected to be the same.
So I try to fix it using null comparison instead of `isset` check.
=> Input: considering nested array keys in `get_post` and `post_get`

system/helpers/captcha_helper.php
The image's width and height are always more than 0; so, adding "px" after the width and height is necessary for HTML validation.
=> Add px to width and height for inline style

application/config/user_agents.php
If you use the `agent->is_mobile()` method to render a mobile friendly page, you can still get dinged by google with their mobile rendering test. Though it's still considered a 'googlebot' they updated their user agent string to include 'Nexus' as seen in this blog post:
https://webmasters.googleblog.com/2016/03/updating-smartphone-user-agent-of.html
Adding nexus to the user agent string allows the method to correctly display mobile screens to googlebots when google is using the mobile user agent.
=> Added mobile google bot to user agents

system/database/drivers/oci8/oci8_forge.php
When I ran the following code, the NOT NULL constraint of the target column did not come off.
```php
$this->dbforge->modify_column('EXAMPLE', [
'COLUMN_1' => [
'null' => true,
],
'COLUMN_2' => [
'null' => true,
]
]);
```
**Expected query**
```sql
ALTER TABLE "EXAMPLE" MODIFY (
"COLUMN_1" NULL,
"COLUMN_2" NULL)
```
**Actual query**
```sql
ALTER TABLE "EXAMPLE" MODIFY (
"COLUMN_1",
"COLUMN_2")
```
**Execution environment**
Oracle 12c
PHP 7.2
=> Fixed bug that can not be changed from not null to null in oci.

user_guide_src/source/helpers/form_helper.rst
Corrected an example mistake where the input script tries to echo `<p>fieldset content here</p>\n` but the result in "Produces" is `<p>form content here</p>` which is clearly an inconsistant result.
=> Corrected example mistake

system/libraries/Session/drivers/Session_redis_driver.php
This PR tries to provide a better design of session key get_lock design, mentioned in #5382 and by @sskaje .
The previous design may fail when multiple threads are trying the access the same session at nearly the same time. Most of the threads will be killed.
Although this behavior may be corrected by adding checks in custom CI controllers or custom CI libraries, in my understanding session operations in CI controllers should never fail because of one issue come from the driver. In other words, race conditions should be handled in the driver.
BTW, I have completely read that issue and related discussions. As for >300s / no-TTL problem, every lock is going to have TTL, except someone tries to operate sessions by himself, not by the driver IMO.
If this does happen, then he totally deserves …
=> Resolve race condition in redis driven session key get_lock

user_guide_src/source/_themes/sphinx_rtd_theme/static/js/theme.js
replace the function toggle() that has already been removed from jQuery.
This can make the button on the top right corner of the user guide able to use.
#5452
=> [user guide] replace toggle() to fix the toc button

system/libraries/Session/drivers/Session_files_driver.php
`CI_Session_files_driver::open` should return `$this->_failure` on fail scenarios, instead of throwing exceptions.
=> Session files driver to return the failure status code instead of Exception throwing

system/libraries/Session/drivers/Session_redis_driver.php
`$this->php5_validate_id()` should be called after `$this->_redis` is set.
=> Alter php5_validate_id()

system/libraries/Session/drivers/Session_redis_driver.php
In the new version of php-redis since `5.0.0`, some of the methods have been deprecated, like `Redis::setTimeout` and `Redis::delete`. Also, `Redis::ping` now returns `TRUE` (#5801).
=> Adapt to new version of php-redis

composer.json
This PR fixes following deprecation warning by replacing
mikey179/vfsStream to mikey179/vfsstream.
https://travis-ci.org/bcit-ci/CodeIgniter/jobs/584604656#L145
```
Deprecation warning: require-dev.mikey179/vfsStream is invalid,
it should not contain uppercase characters.
Please use mikey179/vfsstream instead.
Make sure you fix this as Composer 2.0 will error.
```
=> Fix deprecation warning on Travis

system/database/DB_query_builder.php
There was an issues when using count_all_results with query builder. The select portion of query gets overwritten making the fields referenced in having not existent 
Signed-off-by: Najdanovic Ivan <najdanovicivan@gmail.com>
=> Fix count_all_result if QB query contains Having

.travis.yml
This is php5.3 supported version of #5836 to `3.1-stable` branch.
=> Update Ubuntu version from Precise to Trusty on Travis with PHP5.3 support

.travis.yml
Travis warns about old ubuntu version, now.
https://travis-ci.org/bcit-ci/CodeIgniter/jobs/584604656
Actually, the support of Precise(12.04) is ended at April 2017.
It might be better to update Xenial(16.04), but php5.4 and php5.5
are not supported in Xenial, thus, this PR updates to Trusty(14.04)
which is supported until April 2022.
https://docs.travis-ci.com/user/reference/xenial/#php-support
https://wiki.ubuntu.com/Releases.
By updating to Trusty, we could test 7.4snapshot version and 
8.0.0-dev version easily, thus I added them.
This pr also replace `php:hhvm` to `php:hhvm-3.30`.
Because composer is not support hhvm any more as
https://github.com/composer/composer/issues/8127,
thus, composer cause the error in hhvm-4.
It would be better to test in hhvm-3.30 which is the
last php …
=> Update Ubuntu version from Precise to Trusty on Travis

system/helpers/captcha_helper.php
While moving to a different server, I noticed that `create_captcha()` was returning `false`, and since there was no logging made, I had to change manually the captcha helper to do some step-by-step debugging. It turned out that php-gd wasn't installed.
Since I'm already touching it, I added some logging for the scenario where img_path wouldn't be writable, as well.
=> Improve create_captcha()'s logging

.gitattributes
Exclude `user_guide` directory if package is installed with composer with the --prefer-dist flag set.
Reff: https://github.com/bcit-ci/CodeIgniter/issues/5843
=> Exclude user_guide directory from composer installation by GitAttributes.

system/libraries/Cache/drivers/Cache_redis.php
PhpRedis is installed as redis. Change matches the check in the Redis session driver.
=> cache: redis: Check version of redis not phpredis

system/database/drivers/oci8/oci8_forge.php, system/database/drivers/pdo/subdrivers/pdo_oci_driver.php, system/database/drivers/pdo/subdrivers/pdo_oci_forge.php
Added the function to use AUTO_INCREMENT using Oracle 12.1 `GENERATED ALWAYS AS IDENTITY`.
You can check with the following code.
```php
$this->dbforge->add_field([                                                                           
'AI_COLUMN' => [
'TYPE' => 'NUMBER',
'CONSTRAINT' => '2',
'auto_increment' => true,
],
'NOT_AI_COLUMN' => [
'TYPE' => 'NUMBER',
'CONSTRAINT' => '2',
],
]);
$this->dbforge->create_table('DUMMY');
```
=> Enhancement oracle dbforge, auto_increment can be used when using oracle 12.1.

system/libraries/Zip.php
This PR is submitted in order to solve issue #5864, as per @vlakoff's suggestion. It aims to stop the ZIP Library from allocating unnecessary memory on the get_zip() function. 
Signed-off-by: Andrés Ignacio Torres <andresitorresm@gmail.com>
=> ZIP Library Memory Optimization

system/database/DB_driver.php, user_guide_src/source/database/db_driver_reference.rst
Currently there is no mechanism to determine if a transaction is currently active. This function, by allowing read-only access to the protected `_trans_depth` property, can be used to determine if a transaction is currently active, if the transaction is nested, and how many levels of nesting are in effect.
For my personal use case I only need to know if a transaction is active or not, however rather than create a `trans_active()` function or similar I felt it was better to just return the underlying `_trans_depth` as there may be cases where determining if a transaction is nested is useful. It also provides for an obvious function name and I was happy to not have to choose the right name for a `trans_active`-type function.
=> Adds a public trans_depth function to determine transaction state

system/core/Common.php
In some Apache servers running the `HTTP/2` protocol, calling `$_SERVER['SERVER_PROTOCOL']` may return `HTTP/2.0` instead, thus causing CodeIgniter to (incorrectly) determine the output header protocol to use. This commit adds the different variation value to fix that.
=> Add server protocol value variation

system/database/drivers/pdo/pdo_driver.php
We discovered a resource leak (database connection leak) in our application's test suite. We investigated and discovered that, although the test suite was calling `CI_DB_driver::close()` after each test, the `result_id` member variable still maintained an internal reference to the database connection, which kept the connection from being closed.
This is using pdo_sqlsrv; I have not tested other PDO drivers.
This PR addresses the problem by clearing `result_id` within CodeIgniter's PDO driver's `_close` method, but if another approach would be better, please let me know.
=> Fix database connection leak when closing PDO connection

system/libraries/Image_lib.php
Due to this pr https://github.com/bcit-ci/CodeIgniter/pull/5883 while changing the function `image_create_gd` to add support for webp, the option to create a resource from png is no longer possible.
=> Fixed issue with creating a resource from png using Image_lib

.travis.yml, tests/codeigniter/helpers/text_helper_test.php
By coping the file ('application/config/foreign_chars.php') directly, travis test in php7.4 are passed.
I guess that there are some encoding errors in `ci_vfs_clone` for cloning the UTF-8 file in php7.4.
The error was just a coping the file for creating test-environment, thus,
we could consider that CodeIgniter itself could pass php7.4 travis test, I guess.
EDIT: I add composer cache in Travis, because composer downloading causes error sometimes.
=> Pass the travis php7.4 test

.gitattributes
Excludes `user_guide_src` via `--prefer-dist` composer installation. 
Refer to this https://github.com/bcit-ci/CodeIgniter/issues/5843#issuecomment-889615837 based on this https://github.com/bcit-ci/CodeIgniter/pull/3831.
> This basically just removes a number of development-only files (like the user guide source and our tests) from any installs made through composer with the --prefer-dist flag set.
> 
> Helps create a faster install with less unnecessary files to new projects.
=> Updates .gitattributes, added export-ignore.

.travis.yml, composer.json, tests/Bootstrap.php, tests/codeigniter/Setup_test.php, tests/codeigniter/core/Input_test.php, tests/codeigniter/database/query_builder/select_test.php, tests/codeigniter/helpers/file_helper_test.php, tests/codeigniter/helpers/text_helper_test.php, tests/mocks/ci_testcase.php, tests/phpunit.xml
Lately, the Travis builds were not so green. :P This PR addresses that.
* Added PHPUnit 8 as a potential PHPUnit version. This also sets up the ground for adding in a future PR PHP 8 in the Travis pipeline
* Upgraded to latest vfsstream. The `if` added in #5946 was removed, as it seems there's no issue with PHP 7.4 in latest version.
* `-d mbstring.func_overload=7` is added conditionally now, only if PHP < 7.3
* PHPUnit's `TestCase`'s `void` return type hints were removed to maintain compatibility. This approach was inspired by one of symfony's phpunit bridge features
* other fixes
As already being said, this is a ground for adding PHP 8 in the Travis pipeline, in another separate PR, with test fixes that will most probably come as well.
=> Fixes Travis pipeline. Adding PHPUnit 8.

application/config/mimes.php
Some MIME detection programs/libraries identify SVG files without `<?xml ...?>` declaration as `image/svg`
=> Added another SVG mimetype

system/database/drivers/oci8/oci8_driver.php
I ran the following error when I ran about 3000 unit tests.
ORA-01000
The cause is that the cursor became huge because `oci_free_statement` was not performed.
This code reduced the oracle open cursor by a factor of ten.
I can't submit the actual test code, but I don't think this implementation will cause a bug.
I measured the number of cursors with the following SQL.
```
select   sid,   statistic#,   value from v$sesstat where statistic# = 5   and sid in (select sid from v$session where username ='test');
```
=> fix too many connection for oracle

system/core/Loader.php, tests/codeigniter/core/Loader_test.php
Signed-off-by: Christian Mohr <christian.mohr@insitu.de>
I propose to prevent variables from the second `$this->load->view()` parameter `$vars` to get stored within the `$this->_ci_cached_vars` cache. This cache should only be filled from a corresponding `$this->load->vars()` call and respectively cleared via `$this->load->clear_vars()`if desired. This would be the behaviour expressed within the [documentation](https://www.codeigniter.com/user_guide/libraries/loader.html?highlight=view#CI_Loader::view).
**Background**: The documentation states, that global view parameters could be set via `vars()` and afterwards used within all views without further requirements. This store can be cleared via `clear_vars()` if necessary. The `CI_Loader::view()` method provides an alternative approach for …
=> prevent _ci_vars from being cached in _ci_cached_vars

system/database/DB_driver.php
While creating a SQL query string using query builder,  NOT BETWEEN operator adds a syntax error, Solution added to _has_operator() and _get_operator() method.
=> NOT BETWEEN syntax error DB where() issue solved

system/libraries/Session/Session_driver.php
Fixes Passing null to parameter #2 ($value) of type string is deprecated
=> Fix passing NULL to setcookie value parameter

system/libraries/Profiler.php
check for null value on $val
for this warning : 
`Message: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated`
I think there might be more cases, but I only fixed the case I ran into. (also not sure if this is a valid style of fixing)
=> profiler.php PHP 8.1 deprecation notice 

system/libraries/Ftp.php
Was returning incorrect result for valid connection making it impossible to use FTP
=> Fix method _is_conn() in Ftp library
