tests/codeigniter/core/Lang_test.php
tests/mocks/ci_testcase.php

Here's a little unit test for the error reported in #3464 ...
Signed-off-by: Dan Bernardic <dan.bernardic@gmail.com>

Added a unit test for #3464

---

.travis.yml
tests/codeigniter/core/Output_test.php
tests/mocks/database/schema/skeleton.php

Signed-off-by: Dan Bernardic <dan.bernardic@gmail.com>

Added support for running unit tests on PHP 5.2

---

system/libraries/Image_lib.php

imageAlphaBlending
imageSaveAlpha

We can preserve transparency for PNG images

---

user_guide_src/source/installation/upgrade_300.rst

A few additional notes:
* For robustness and simplicity, we may replace relative paths `<../libraries/loader>` with absolute paths `</libraries/loader>`.
* @narfbg I was planning to end compiling the documentation by myself and just use the online version. You should verify that your changes compile correctly.

Fix Sphinx broken path

---

system/database/drivers/pdo/subdrivers/pdo_4d_forge.php
system/database/drivers/pdo/subdrivers/pdo_mysql_forge.php
system/database/drivers/sqlite3/sqlite3_result.php

Hello,
- database/drivers/pdo/subdrivers/pdo_mysql_forge.php : 
- This $comment_clause local variable is declared but never used.
- database/drivers/pdo/subdrivers/pdo_4d_forge.php :
- Fix error extends class name
- database/drivers/sqlite3/sqlite3_result.php : 
- Corrected loop with the good variable

Database Driver Clean and Fix

---

user_guide_src/source/general/ancillary_classes.rst

Small fixes in documentation

---

user_guide_src/source/general/credits.rst

Fixed spelling mistake in documentation.

Fixed #3516

---

system/core/Common.php

is_php() more accurate description

is_php() more accurate description

---

system/libraries/Image_lib.php

Fixes #3536.
Also includes minor fix in positioning of the watermark text when using drop shadow.

Fixed watermark function to work without drop shadow

---

user_guide_src/source/general/errors.rst

Verified that the user guide build works.

Clarified the template folder for errors.

---

system/core/Output.php

Signed-off-by: natepizzle <natepizzle@users.noreply.github.com>

Documentation Fix

---

application/views/errors/html/error_404.php
application/views/errors/html/error_db.php
application/views/errors/html/error_general.php
application/views/welcome_message.php

Removed -webkit-selection

---

system/database/drivers/mssql/mssql_result.php
system/libraries/Encryption.php

I found some typos in function calls

Fix typos in func names

---

user_guide_src/source/_themes/sphinx_rtd_theme/static/js/oldtheme.js
user_guide_src/source/_themes/sphinx_rtd_theme/static/js/theme.js

Integrating Rufnex's Javascript optional menu replacement :)
Now you will see a small icon in the top right of the user guide browser window. Clicking this toggles between the readdocs style TOC, in the left sidebar, and the "classic" CI TOC, a pulldown activated by clicking on the "Table of Contents" icon at the top of the browser window. The tool use a cookie to remember your decision.
Integrated on behalf of .... -- Have fun! Rufnex - codeigniter.de

Add pulldown menu to user guide.

---

user_guide_src/source/helpers/form_helper.rst

some missed explanation on set_value()

---

application/cache/index.html
application/language/english/index.html
application/views/errors/cli/index.html
application/views/errors/html/index.html
application/views/errors/index.html
system/database/drivers/index.html
system/language/english/index.html
system/libraries/Session/drivers/index.html

Some of the files index.html were not updated, I am doing it.

Finishing PR #3596 <!DOCTYPE html>

---

system/libraries/Cache/drivers/Cache_redis.php
system/libraries/Cache/drivers/Cache_wincache.php

1. Cache_redis: Standardize the style as other driver.
2. Cache_wincache:  Also check wincache.ucenabled

Cache: is_supported

---

system/core/Common.php

1. Verify $code before define $stati
2. Only convert $code to int and define $stati when needed, possibly can
save some memory.

Common.php: set_status_header: Improve

---

user_guide_src/source/installation/upgrade_300.rst

last step count should be 20......

fix wrong step count

---

user_guide_src/source/database/results.rst

Small typo

---

tests/codeigniter/core/Security_test.php

Unit test for strip_image_tags function in Security.php added.

Add Ci security unit test

---

system/libraries/Form_validation.php

The checking is done in the compat file system/core/compat/mbstring.php

Reduce once MB_ENABLED checking

---

tests/codeigniter/core/Security_test.php

Improved Code Coverage from 54.55% to 77.27% for CI_Security.

Updated CI Security unit test 

---

user_guide_src/source/helpers/html_helper.rst

additional info on heading() function

---

tests/codeigniter/core/Input_test.php

added a few more tests to cover fetch_from_array fully.
Signed-off-by:Heesung Ahn <ahn.heesung@gmail.com>

Updated fetch_from_array unit test

---

system/core/Input.php
tests/codeigniter/core/Input_test.php

The error was caused by using the same variable name, $i, twice for for loop inside for loop.
Signed-off-by:Heesung Ahn <ahn.heesung@gmail.com>

Updated CI_Input unit test and fixed error "undefined offset" 

---

system/libraries/Calendar.php

Fixes http://forum.codeigniter.com/thread-1552.html
Broken since 8d5b24a8c55dc1ae7721e10de094c4aba2ca7eae

Fix language overriding for calendar library

---

system/libraries/Form_validation.php
tests/codeigniter/libraries/Form_validation_test.php

Added setup and tests for all rules specified in the documentation.
Several test cases currently fail. I'll create bug issues & fixes once this pull request is accepted.
Signed off:
djwoods <d.woods92@gmail.com>

Added CI_Form_validation unit tests

---

user_guide_src/source/tutorial/static_pages.rst

Fix an example in the tutorial.

---

system/core/URI.php

Signed-off-by: Cyrille TOULET <cyrille.toulet@linux.com>

Fix an "strpos(): Empty needle" warning

---

tests/codeigniter/core/Loader_test.php

Signed-off-by:Heesung Ahn <ahn.heesung@gmail.com>

Improved unit test code coverage.

---

tests/codeigniter/core/Lang_test.php

Unit test lang test

---

system/core/Loader.php

This is to fix a logged path missed in
8f5c1780706113c926bb7801db27dbae97d00fcf

Fix logged path to match checked path in loader

---

system/core/Common.php

sync [Status Code](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)

Sync Status Code Definitions

---

tests/codeigniter/helpers/email_helper_test.php

Just adding a test for a valid email address.

Add test for email address with subdomain

---

user_guide_src/source/libraries/migration.rst

version 1 does not work when you use Timestamp.

Fix migration_version

---

system/libraries/Cache/drivers/Cache_redis.php

https://github.com/phpredis/phpredis#set

[Cache]minor adjustments for save function

---

user_guide_src/source/libraries/file_uploading.rst

add param to do_upload() function.

param missing.

---

user_guide_src/source/libraries/image_lib.rst

Fixed some grammar mistakes in image_lib.rst

Fixed some grammar.

---

system/libraries/Migration.php
user_guide_src/source/libraries/migration.rst

[Code](https://github.com/bcit-ci/CodeIgniter/blob/develop/system/libraries/Migration.php#L194) and [User Guide](http://www.codeigniter.com/user_guide/libraries/migration.html#CI_Migration::version) keep the consistency.

optimize migrations class reference

---

application/config/mimes.php

Added .ico mime type

---

user_guide_src/source/database/forge.rst

Typo fix on forge documentation

---

system/libraries/Unit_test.php
user_guide_src/source/libraries/unit_testing.rst

```php
$lang['ut_resource'] = 'Resource';
```
so added.

Added "is_resource" into the list of unit tests capable of being run.

---

user_guide/general/cli.html

Corrected spelling mistake of Lunix to Linux.

Update cli.html for spelling mistake

---

user_guide_src/source/libraries/output.rst

Fix sample code

---

application/views/errors/cli/error_php.php

Before:
~~~
$ php index.php 
Parse error: syntax error, unexpected '$this' (T_VARIABLE) in /Users/kenji/work/codeigniter/CodeIgniter/application/controllers/Welcome.php on line 24
Call Stack:
0.0053     228344   1. {main}() /Users/kenji/work/codeigniter/CodeIgniter/index.php:0
0.0183     233128   2. require_once('/Users/kenji/work/codeigniter/CodeIgniter/system/core/CodeIgniter.php') /Users/kenji/work/codeigniter/CodeIgniter/index.php:292
A PHP Error was encountered
Severity: Parsing ErrorMessage:  syntax error, unexpected '$this' (T_VARIABLE)Filename: /Users/kenji/work/codeigniter/CodeIgniter/application/controllers/Welcome.phpLine Number: 24
Backtrace:
$ 
~~~
After:
~~~
$ php index.php 
Parse error: syntax error, unexpected '$this' (T_VARIABLE) in …

Fix errors/cli/error_php.php output

---

application/config/routes.php

I found the original text of the routing dash replacement documentation to be lacking, even though the example cleared things up. This small change addresses the lack of clarity in the text, minor as it is.
Thank you!

Specify to which character dashes will be replaced

---

system/database/DB_driver.php

Stable version has an extra = sign in the beginning of a database php file.

There was an extra = sign in this file

---

user_guide_src/source/_themes/sphinx_rtd_theme/static/js/theme.js
user_guide_src/source/changelog.rst

Fixed the pulldown nav, issue #4043

---

user_guide_src/source/libraries/calendar.rst

forget to close a tag cal_cel_other

cal_cel_other

---

user_guide_src/source/index.rst

Rearrange the TOC slightly, to support consistency between the side menu and the sphonx toctree-derived pulldown menu.

Adjust user guide TOC

---

system/core/Config.php
tests/codeigniter/core/Config_test.php

Refactor exception handling in core/Config

---

system/core/Lang.php
user_guide_src/source/libraries/language.rst

add user guide change for #4216 as suggested by @jim-parry 
part of #4189

add user guide change for core/security exception refactoring

---

user_guide_src/source/libraries/form_validation.rst

Fix another file name in documentation according PR #4271

fix another file name according PR #4271

---

system/core/Router.php
system/core/URI.php

fix phpdoc with Router.php, URI.php
This PR to big open source project is for the first time for me.
So I will apologize if I mistake PR process.

fix phpdoc

---

system/helpers/path_helper.php
tests/codeigniter/helpers/path_helper_test.php
user_guide_src/source/helpers/path_helper.rst

refactor show_error to InvalidArgumentException

refactor error enhandling of path_helper

---

system/core/Loader.php
system/database/DB_driver.php
user_guide_src/source/changelog.rst

As we discussed yesterday with narfbg, I modified my last solution. Now we throw a RuntimeException instead of returning FALSE.
I also added this modification to the changelog.

throwing RuntimeException instead of returning FALSE

---

application/config/user_agents.php

added Vivaldi browser

---

user_guide_src/source/installation/upgrade_300.rst

Renamed Step 20 to Step 21

---

system/helpers/html_helper.php
tests/codeigniter/helpers/html_helper_test.php
user_guide_src/source/helpers/html_helper.rst

HTML Helper - meta(): now can generate HTML meta charset & Open Graph property

HTML Helper -> HTML 5

---

user_guide_src/source/installation/upgrade_300.rst

Fix formatting of paths

---

user_guide_src/source/database/forge.rst

Issue: #2989
Added unique field attribute to the documentation.

Added Unique Field Attribute Doc

---

system/database/DB_query_builder.php

Edit of some return type in phpdoc. This can also help to fix some autocompletion troubles in some IDE.

Update DB_query_builder.php - phpdoc (some incorrect return type)

---

application/config/autoload.php
system/core/Loader.php

Updated loader to autoload drivers with object names the same as autoloading libraries.

Autoload Driver Object Names

---

user_guide_src/source/libraries/image_lib.rst

> at *the* same level *as*
Sorry to open new PR, i just try my best.
Since a lot of thing i do but can't achieve that in last 10 hours.
I know i am stupid :confused: , hope this help the others.

Doc , update image_lib.rst

---

system/libraries/Cache/drivers/Cache_memcached.php

Added variables to Docblocks where they are skipped.

Added variables to Docblocks (memcached)

---

user_guide_src/source/tutorial/static_pages.rst

Removing forward slash since `APPPATH` ends with `DIRECTORY_SEPARATOR`.

Removing character

---

user_guide_src/source/helpers/inflector_helper.rst

Reported by email from Jessie Rubi

Fix typo in inflector helper writeup.

---

application/config/user_agents.php

Added Majestic-12 and Uptimebot

Update robots in config/user_agents.php

---

system/database/drivers/oci8/oci8_forge.php
system/database/drivers/pdo/subdrivers/pdo_oci_forge.php

* Oralce does not have `create table if exists`
* Oracle has only NUMBER for integer

Fix oci8_forge

---

system/libraries/Form_validation.php
system/libraries/Trackback.php
system/libraries/Xmlrpc.php

URI schemes are not case sensitive.

URI scheme case

---

system/helpers/url_helper.php
system/libraries/Form_validation.php
system/libraries/Javascript.php

#4758 
_Grepping_ the source revealed a few more similar bugs.
Signed-off-by: Vivek Dinesh <vivekdinesh5@gmail.com>

URI schemes are not case-sensitive

---

system/libraries/Email.php

return fix

---

system/core/compat/hash.php

Original `hash_pbkdf2()` allows upper-case algorithm name.

Hash: processing algorithm name case-insensitively in hash_pbkdf2()

---

application/config/mimes.php

According to IANA media types : http://www.iana.org/assignments/media-types/media-types.xhtml

OpenOffice mime-types

---

system/libraries/Cache/drivers/Cache_redis.php

Add redis database index by default
Select database if exists

Add redis database index by default

---

system/database/DB_driver.php
system/database/drivers/odbc/odbc_driver.php

Fix pull request [4886](https://github.com/bcit-ci/CodeIgniter/pull/4886)

Fix compile_binds: do not use back references inside a character class.

---

tests/codeigniter/helpers/inflector_helper_test.php

Added 7 test-cases for ordinal_format(). :)

Unit-testing for ordinal_format() (Inflector helper)

---

system/helpers/text_helper.php

Just noticed the bump of PHP minimum version :-)
So it should be a good moment to make the code here a bit less complicated. Follow-up to #1750, see notably this [comment](https://github.com/bcit-ci/CodeIgniter/pull/1750#issuecomment-8279512).

Small code simplification in character_limiter()

---

system/libraries/Email.php

Signed-off-by: Kristaps V kristaps@viitols.com

Fix custom user agent not working

---

system/helpers/download_helper.php

Move duplicate is_file and filesize checks out of if/else branches.

Don't duplicate is_file and filesize checks

---

system/database/DB_query_builder.php
tests/codeigniter/database/query_builder/group_test.php
user_guide_src/source/database/query_builder.rst

For generating SQL query such as 
`SELECT country, count(1) FROM user GROUP BY country HAVING count(1) IN(2, 3) OR country NOT IN('US', 'UK')`

DB_query_builder: Adding having_in(), or_having_in(), having_not_in() and or_having_not_in()

---

system/libraries/Cache/Cache.php
user_guide_src/source/libraries/caching.rst

New Cache.php method added, for finding out which caching driver was loaded; Updated docs as well.

New Cache method: get_loaded_driver()

---

system/libraries/Xmlrpc.php

Fix typo in serializeval()

---

system/helpers/inflector_helper.php

quizzes singular is doesnt work.

---

system/core/Common.php
system/core/Exceptions.php
system/core/compat/mbstring.php
system/database/DB_forge.php
system/database/drivers/ibase/ibase_forge.php
system/libraries/Session/drivers/Session_redis_driver.php
system/libraries/Table.php

Various issues were detected by a static analyzer

Fix misc inconsistencies between code and doc comments

---

system/libraries/Profiler.php

.. in config and session when array

Profiler add pre tag

---

system/database/DB_query_builder.php

add NATURAL JOIN types
relation issues are  #5240 and #5239

add NATURAL JOIN types

---

system/database/drivers/pdo/subdrivers/pdo_dblib_driver.php

I was testing a feature and needing it using LIMIT / OFFSET and I had to make this fix, if you could include it in the core project, maybe it would help others.

Fix for DBLIB subdriver to get the right version number of SQL Server.

---

user_guide_src/source/database/queries.rst

$this->db->set_dbprefix('newprefix');
$this->db->dbprefix('tablename');
Would output newprefixtablename not newprefix_tablename

Fixed dbprefix() documentation

---

system/core/Common.php

According to [Hypertext Transfer Protocol (HTTP) Status Code Registry](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml),complement the missing HTTP status codes

complement the missing HTTP status codes

---

system/database/DB_query_builder.php
tests/codeigniter/database/query_builder/like_test.php

Fixed issue #5462 Query Builder LIKE BEFORE doesnt work

---

user_guide_src/source/installation/upgrade_319.rst

corrected the serial number of 'source/installation/upgrade_319' and changed the heading size

corrected the serial number of 'source/installation/upgrade_319'

---

system/helpers/html_helper.php
system/libraries/Cache/drivers/Cache_file.php

Change comparison operator to assignment, which it should be.

Fix html helper

---

.travis.yml

Thank you for your continuous development!
This is just adding php7.3 tests on travis.

Add PHP 7.3 tests on Travis

---

user_guide_src/source/libraries/form_validation.rst

Error was on page: https://codeigniter.com/user_guide/libraries/form_validation.html

Punctuation error fixed in documentation (add apostrophe).

---

application/config/user_agents.php

Added Meizu agent in Manufacturers
https://www.meizu.com/

Added Meizu agent in Manufacturers

---

user_guide_src/source/tutorial/static_pages.rst

Fix typo in Tutorial

---

system/core/Log.php
tests/codeigniter/core/Log_test.php

Window's Notepad doesn't recognize `\n` linebreak it has to be `\r\n`

Adding support for proper CRLF

---

system/libraries/Cache/drivers/Cache_redis.php

We ran this for about 2 weeks without issue. It keeps the group and works completely with whats there currently.
This may be the "optimized" the version you were talking about.
Its major drawback is that is only works correctly in the default set up for redis. the other PR correctly fixes this for all options in redis.

Alterntive redis fix

---

system/libraries/Cache/drivers/Cache_redis.php

also fixed a value incorrectly returned docblock says array but bool returned

Fix increment / decrement in redis

---

system/libraries/Session/drivers/Session_redis_driver.php

Fixes php5_validate_id() method calling from Redis session driver

---

user_guide_src/source/tutorial/create_news_items.rst

Input is not a valid value for the type attribute for an input tag. Replaced with text, a valid value.
https://www.w3schools.com/tags/att_input_type.asp

Fixed HTML type attribute for input field.

---

application/config/user_agents.php

Fix for #5711 and added two more models.
1. Vivo
2. Oppo

Fix for #5711 and added two more models

---

application/views/welcome_message.php
system/database/DB.php
system/database/drivers/ibase/ibase_forge.php
system/database/drivers/pdo/pdo_driver.php
system/database/drivers/pdo/subdrivers/pdo_firebird_forge.php
system/database/drivers/pdo/subdrivers/pdo_pgsql_forge.php
system/database/drivers/postgre/postgre_forge.php
system/libraries/Cache/drivers/Cache_apc.php
system/libraries/Cache/drivers/Cache_apcu.php
system/libraries/Cache/drivers/Cache_dummy.php
system/libraries/Cache/drivers/Cache_wincache.php
system/libraries/Profiler.php
tests/codeigniter/helpers/file_helper_test.php
tests/mocks/autoloader.php
tests/mocks/ci_testcase.php

Fix indent

---

application/config/user_agents.php

added ininfix manufacture in user_agents.php
http://www.infinixmobility.com/

Added Infinix manufacture in user_agents.php

---

system/libraries/Cache/drivers/Cache_redis.php

field with name $_delete_name already defined, use $_sRemove_name

fix static field name

---

user_guide_src/source/libraries/parser.rst

Fix description of parameter $template in method parse_string.

Update documentation for method parse_string

---

system/database/DB_query_builder.php
user_guide_src/source/database/query_builder.rst

fixes https://github.com/bcit-ci/CodeIgniter/issues/5868

Added FULL OUTER JOIN to QueryBuilder

---

application/config/mimes.php

Found two errant double spaces in mimes.php, fixed herein.

Fixed double spacing in mimes.php

---

application/config/mimes.php

Add heic and heif format for Apple file.

Update with heic format

---

application/config/user_agents.php

Add UptimeRobot user agent, a free website monitor.
https://uptimerobot.com/

Add UptimeRobot user agent

---

readme.rst

Issue #5761 asked for an improvement to the root readme file.
This is very simple tweak; however, I think it accomplishes the goal for everyone, without any bloating of the root readme.

chore: Add to main readme contribute guide link

---

application/config/config.php
system/core/Log.php

Signed-off-by: jonsmith1982  - Sorry, I sent a patch to fix this in the original post. Just getting used to git and how best to do things.

fixes #5648

---

system/core/Output.php

Fixes https://github.com/bcit-ci/CodeIgniter/issues/6089

Default $final_output to string instead of NULL

---

system/database/DB_utility.php

Fixes https://github.com/bcit-ci/CodeIgniter/issues/6091

Fix PHP 8.1 deprecation in DB_utility.php
